name = "backend"
compatibility_date = "2024-07-29"

DATABASE_URL="postgres://avnadmin:AVNS_ZCITOvJIyg700jtq7T3@pg-80981f1-tarunkumbhar1998-13c7.e.aivencloud.com:10625/defaultdb?sslmode=require"

[vars]
DATABASE_URL=""
JWT_SECRET=""

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"